Pytest: Creating an organization fails
Creating an organization with an id throws the following error:

"TypeError: __init__() got an unexpected keyword argument 'id'"

This occurs because the organization model doesn't have an
parameter for id.