Playwright binary is owned by `user` (kaniko builds) (#985)
Refactor the Containerfile to ensure user creation occurs before copying
the virtual environment.

This fixes an issue that is not exposed in Docker Buildx, but when
building using [kaniko](https://github.com/osscontainertools/kaniko),
this was a problem.

```
INFO[0526] Taking snapshot of full filesystem...        
INFO[0562] RUN groupadd user &&     useradd --home-dir /app -g user user &&     install -d -o user -g user /app/ms-playwright 
INFO[0562] Cmd: /bin/sh                                 
INFO[0562] Args: [-c groupadd user &&     useradd --home-dir /app -g user user &&     install -d -o user -g user /app/ms-playwright] 
INFO[0562] Running: [/bin/sh -c groupadd user &&     useradd --home-dir /app -g user user &&     install -d -o user -g user /app/ms-playwright] 
INFO[0562] Taking snapshot of full filesystem...        
INFO[0572] COPY --chown=user:user ./src/worker/. /app/  
INFO[0572] Taking snapshot of files...                  
INFO[0572] USER user                                    
INFO[0572] Cmd: USER                                    
INFO[0572] RUN playwright install --only-shell chromium 
INFO[0572] Cmd: /bin/sh                                 
INFO[0572] Args: [-c playwright install --only-shell chromium] 
INFO[0572] Util.Lookup returned: &{Uid:1000 Gid:1000 Username:user Name: HomeDir:/app} 
INFO[0572] Performing slow lookup of group ids for user 
INFO[0572] Running: [/bin/sh -c playwright install --only-shell chromium] 
/bin/sh: 1: playwright: Permission denied
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 127
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: command terminated with exit code 127
```

This fix is tested on kaniko, preserves good cache management, and
should not introduce additional image layers.